-- 10
SELECT NAME, AUFGABE, GEHALT, BEURTEILUNG
FROM PERSONAL
WHERE PERSNR IN (
    SELECT PERSNR
    FROM AUFTRAG
    WHERE AUFTRNR IN (
        SELECT AUFTRNR
        FROM AUFTRAGSPOSTEN
        WHERE GESAMTPREIS = (
            SELECT MAX(GESAMTPREIS)
            FROM AUFTRAGSPOSTEN
        )
    )
)