-- 12
SELECT NAME, P.AUFGABE, P.GEHALT, P.BEURTEILUNG, A.BEZEICHNUNG, A.PREIS
FROM PERSONAL P
WHERE P.PERSNR IN (
    SELECT PERSNR
    FROM AUFTRAG A, AUFTRAGSPOSTEN AP, ARTIKEL AT
    WHERE A.AUFTRNR IN (
        SELECT AUFTRNR
        FROM AUFTRAGSPOSTEN
        WHERE GESAMTPREIS = (
            SELECT MAX(GESAMTPREIS)
            FROM AUFTRAGSPOSTEN
        )
    ) AND AUFTRNR = AP.AUFTRNR
    AND AT.ANR = AP.ARTNR
)