-- 7a)
SELECT NAME
FROM KUNDE
WHERE NR IN (SELECT KUNDNR FROM AUFTRAG WHERE AUFTRNR=1);

-- 7b)
SELECT NAME
FROM PERSONAL
WHERE PERSNR IN (SELECT PERSNR FROM AUFTRAG WHERE AUFTRNR=1);

-- 7c)
SELECT ARTNR, BEZEICHNUNG
FROM AUFTRAGSPOSTEN
JOIN ARTIKEL ON ARTNR = ANR
WHERE AUFTRNR IN (
    SELECT AUFTRNR
    FROM AUFTRAG
    WHERE KUNDNR=(
        SELECT KUNDNR FROM AUFTRAG WHERE AUFTRNR=1
    )
);