-- 24
SELECT L.NAME
FROM LIEFERANT L
WHERE NOT EXISTS (
    SELECT LF1.ANR
    FROM LIEFERUNG LF1
    WHERE LF1.LIEFNR = 3
    MINUS
    SELECT LF2.ANR
    FROM LIEFERUNG LF2 
    WHERE LF2.LIEFNR = L.NR
);