-- 1
ALTER TABLE Personal
DROP CONSTRAINT FK_Personal_Personal;

ALTER TABLE Auftrag
DROP CONSTRAINT FK_Auftrag_Kunde
DROP CONSTRAINT FK_Auftrag_Personal;

ALTER TABLE Auftragsposten
DROP CONSTRAINT FK_Auftrag_Auftrag;

DROP TABLE Kunde;
DROP TABLE Auftrag;
DROP TABLE Personal;
-- ODER
DROP TABLE Kunde CASCADE CONSTRAINTS;
DROP TABLE Auftrag CASCADE CONSTRAINTS;
DROP TABLE Personal CASCADE CONSTRAINTS;