-- 19
-- INNER JOIN entfernt alle Elemente, welche NULL in der Vorgesetzt-Spalte hat.
SELECT P.NAME, (P.GEHALT - P2.GEHALT) AS GEHALTSDIFFERENZ
FROM PERSONAL P
INNER JOIN PERSONAL P2 ON P.VORGESETZT = P2.PERSNR